font=monospace
dpi-aware=auto
fuzzy=yes
# show-actions=no
terminal=foot -e
# launch-prefix=<not set>
list-executables-in-path=yes
anchor=center
# lines=15
# width=30
# tabs=8
# horizontal-pad=40
# vertical-pad=8
# inner-pad=0

# image-size-ratio=0.5

# line-height=<use font metrics>
# letter-spacing=0

layer = top
exit-on-keyboard-focus-loss = yes

[colors]
background=fdf6e3aa
text=657b83ff
match=cb4b16ff
selection=eee8d5dd
selection-text=657b83ff
selection-match=cb4b16ff
background=1D1011ff

[border]
width=1
radius=10
